Add user authorization with cancan gem
Berkay-akbas/My-Blog pull request #10
Opened 2022-11-02 14:46 UTC by Berkay-akbas

# Hello Code Reviewer 👋 

# Changes ♻️ 
- New column "role" added to users table with migration.
- If user is admin they can manage all posts and comments.
- Users now can delete their own posts and comments. Delete button won't be visible if they are not the author.

Thanks for reviewing our code!

2022-11-02 16:23 UTC, OLIPLICHE requested changes
Hi @Berkay-akbas, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Linter is green (the last commit have a green check mark (✅)) 👏
- README file is descriptive 👏
- Commit messages are meaningful 👏 👏
- Gitflow is correctly used 👏


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-02 16:23 UTC, OLIPLICHE commented on app/models/ability.rb
> +end
- Please I need to test your code, Unfortunately, there is an error coming up when trying to Sign up. Kindly fix. 
- 
![Capture](https://user-images.githubusercontent.com/63972670/199543796-32b4ca91-57ab-4848-926a-9ecab9729199.JPG)

2022-11-02 19:05 UTC, Berkay-akbas commented on app/models/ability.rb
> +end
@OLIPLICHE Thanks for the review. I was unsuccessful to recreate the error you are getting. Everything seems to work on my end. I'll just request another review and see what they will get.

2022-11-02 20:14 UTC, codepantha requested changes
# STATUS: REQUIRES CHANGES ♻️ 

## Hi @Berkay-akbas 👋, 

Great work on making the changes requested by the previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

<img src="https://media1.giphy.com/media/xUOxfh6ZM75efM3Bqo/giphy-downsized-medium.gif"/>

## Highlights 🎯 
✔️ Descriptive PR
✔️ No linter errors
✔️ Used GitFlow

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-02 20:14 UTC, codepantha commented on app/models/ability.rb
> +end
- [ ] Just like the previous reviewer highlighted, there's an error 🐛 when creating a new account. It appears that Devise is protesting a redirect. As a result, I am unable to fully test your code. Kindly see the error below 👇 
![image](https://user-images.githubusercontent.com/46839548/199593194-cfbffdbe-94e1-4080-b676-4928283d20c3.png)

2022-11-02 21:23 UTC, Berkay-akbas commented on app/models/ability.rb
> +end
@codepantha Thank you very much. Could you please try again? I think I found the culprit but I'm still unable to test it. It still works on my end.

2022-11-03 09:20 UTC, emmanuellekamwa approved these changes
**STATUS: APPROVED 🍾✔🎉**
Hello @Berkay-akbas and @developerwaleed 👋
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- You documented your work professionally.✔
- You asked for the changes in a polite and friendly way.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-03 09:21 UTC, merged