Integration specs n1 problem
Berkay-akbas/My-Blog pull request #8
Opened 2022-10-31 16:23 UTC by Berkay-akbas

# Hello Code Reviewer 👋 

# Changes ♻️ 
- Integration specs for User Index, User Show, User Post Index, and User Post Show are implemented with a total of 29 tests.
- Solved the n+1 problem which was on post show page.

Thanks for reviewing our code!

2022-10-31 18:05 UTC, uwadonat requested changes
## Hi @Berkay-akbas,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
- Descriptive pull request message ✔️
- No linter errors ✔️
- All you tests are passing ✔️
![almoo](https://user-images.githubusercontent.com/65860678/199078110-b5c343ac-b3eb-418f-b1cb-0488afbe9268.gif)

## Required Changes ♻️
- [ ] Let's solves N+1 problem when fetching all posts and their comments for a user
- _Hint_: Example in the posts#index actions students should use @posts = @user.posts.includes(:comments) instead of @posts = @user.posts

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100%.
Please, remember to tag me @uwadonat in your question so I can receive the notification.

------
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-01 06:56 UTC, Berkay-akbas commented on app/views/posts/index.html.erb
> +<% @user.posts.includes([:comments]).each do |post|  %>
@uwadonat Hello and thank you for the review, Here you can see it in the view file for posts index. It was one of the changes.

2022-11-01 07:10 UTC, sja-thedude approved these changes
## Project Approved 👍 

Hi @Berkay-akbas, This is @sja-thedude your code reviewer.

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Highlights:
- All linters passing
- All requirements completed
- Professional readme

![giphy](https://user-images.githubusercontent.com/70269507/159485323-11dfc0c5-bd53-4956-b55a-2fc42f7a3845.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-01 07:49 UTC, m05e5 approved these changes
Hi @Berkay-akbas , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![goodjob](https://user-images.githubusercontent.com/60631456/130260474-3c2d5e5c-96df-43de-a0db-8d0059c10862.gif)

## Highlights
✔️ your linters are all ok
✔️ Descriptive PR 

## Optional suggestions


_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

_**m05e5**_

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-01 11:02 UTC, merged